### ISSUE TITLE
Stack trace order is inconsistent

### ISSUE THREAD

**Issue by LilithHafner** [JuliaPy/PythonCall.jl#391]
**Is your feature request related to a problem? Please describe.**
Python stack traces place the most recent call last, Julia's place the most recent call first. When I the call stack has a bunch of Python function then a bunch of Julia functions, the most recent call is in the middle. I don't like that.

**Describe the solution you'd like**
It'd be nice if PythonCall printed Python stack traces in julian order and JuliaCall printed julia stack traces in pythonic order.

**Comment by cjdoris** [comment]
But yes, you're right that from Python, the Julia stack is printed in reverse. This is because custom stack printing has not been implemented on that side, so just uses `Base.showerror(io, error, backtrace)`.

```
>>> jl.seval("""begin
...     jlinner() = error()
...     jlouter() = jlinner()
... end""")
Julia: jlouter (generic function with 1 method)
>>> def pyinner():
...     jl.seval("jlouter()")
...
>>> def pyouter():
...     pyinner()
...
>>> pyouter()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in pyouter
  File "<stdin>", line 2, in pyinner
  File "C:\Users\chris\.julia\packages\PythonCall\qTEA1\src\jlwrap\module.jl", line 25, in seval
    return self._jl_callmethod($(pyjl_methodnum(pyjlmodule_seval)), expr)
juliacall.JuliaError:
Stacktrace:
 [1] error()
   @ Base .\error.jl:44
 [2] jlinner()
   @ Main .\none:2
 [3] jlouter()
   @ Main .\none:3
 [4] top-level scope
   @ none:1
 [5] eval
   @ .\boot.jl:370 [inlined]
 [6] eval
   @ .\Base.jl:68 [inlined]
 [7] pyjlmodule_seval(self::Module, expr::Py)
   @ PythonCall C:\Users\chris\.julia\packages\PythonCall\qTEA1\src\jlwrap\module.jl:13
 [8] _pyjl_callmethod(f::Any, self_::Ptr{PythonCall.C.PyObject}, args_::Ptr{PythonCall.C.PyObject}, nargs::Int64)
   @ PythonCall C:\Users\chris\.julia\packages\PythonCall\qTEA1\src\jlwrap\base.jl:62
 [9] _pyjl_callmethod(o::Ptr{PythonCall.C.PyObject}, args::Ptr{PythonCall.C.PyObject})
   @ PythonCall.C C:\Users\chris\.julia\packages\PythonCall\qTEA1\src\cpython\jlwrap.jl:47
```

It would indeed be nice to improve these stack traces.
